In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dict = {"name": ['ABC','DEF','GHI'] ,
      "marks": [32,54,43],
      "branch": ['CSE','MTH','EE']}

In [4]:
dictionary = pd.DataFrame(dict)

In [5]:
dictionary.to_csv('dict.csv')

In [6]:
dictionary.to_csv('dict1.csv',index=False)

In [7]:
df = pd.read_csv('/content/Moons_and_Planets.csv')

In [8]:
df.head(2)

  # Name of Moon  Name of Planet   Diameter (km)
0           Moon           Earth          1737.1
1         Phobos            Mars            11.1

In [9]:
df.tail(2)

    # Name of Moon  Name of Planet   Diameter (km)
208       Kerberos           Pluto            14.0
209           Styx           Pluto            10.0

In [10]:
print(df.columns)

Index(['# Name of Moon', ' Name of Planet', ' Diameter (km)'], dtype='object')

In [11]:
df[' Diameter (km)'].describe()

count     210.000000
mean      112.187762
std       389.180293
min         0.150000
25%         2.000000
50%         4.000000
75%        22.750000
max      2634.100000
Name:  Diameter (km), dtype: float64

In [12]:
dictionary.index = ['first','second','third']

In [13]:
dictionary

       name  marks branch
first   ABC     32    CSE
second  DEF     54    MTH
third   GHI     43     EE

In [14]:
ser = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

In [15]:
ser

a   -1.280376
b    0.070409
c   -1.870862
d    0.560565
e    1.180534
dtype: float64

In [16]:
type(ser)

pandas.core.series.Series

In [17]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [18]:
newdf

            0         1         2         3         4
0    0.296931  0.323951  0.523106  0.214857  0.183593
1    0.326494  0.028997  0.436147  0.706490  0.058738
2    0.597773  0.644591  0.629921  0.420055  0.481585
3    0.350908  0.010103  0.318830  0.019520  0.432900
4    0.723405  0.089767  0.473260  0.706020  0.596523
..        ...       ...       ...       ...       ...
329  0.770204  0.355958  0.113054  0.247160  0.389445
330  0.845090  0.890601  0.863418  0.441534  0.868757
331  0.847442  0.691821  0.014040  0.379885  0.166638
332  0.670260  0.313709  0.536439  0.950113  0.407011
333  0.966893  0.248475  0.639222  0.431007  0.267863

[334 rows x 5 columns]

In [19]:
newdf.head(5)

          0         1         2         3         4
0  0.296931  0.323951  0.523106  0.214857  0.183593
1  0.326494  0.028997  0.436147  0.706490  0.058738
2  0.597773  0.644591  0.629921  0.420055  0.481585
3  0.350908  0.010103  0.318830  0.019520  0.432900
4  0.723405  0.089767  0.473260  0.706020  0.596523

In [20]:
type(newdf)

pandas.core.frame.DataFrame

In [21]:
newdf[3][4]='XYZ'

/tmp/ipython-input-3274821851.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[3][4]='XYZ'
/tmp/ipython-input-3274821851.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'XYZ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[3][4]='XYZ'

In [22]:
newdf

            0         1         2         3         4
0    0.296931  0.323951  0.523106  0.214857  0.183593
1    0.326494  0.028997  0.436147   0.70649  0.058738
2    0.597773  0.644591  0.629921  0.420055  0.481585
3    0.350908  0.010103  0.318830   0.01952  0.432900
4    0.723405  0.089767  0.473260       XYZ  0.596523
..        ...       ...       ...       ...       ...
329  0.770204  0.355958  0.113054   0.24716  0.389445
330  0.845090  0.890601  0.863418  0.441534  0.868757
331  0.847442  0.691821  0.014040  0.379885  0.166638
332  0.670260  0.313709  0.536439  0.950113  0.407011
333  0.966893  0.248475  0.639222  0.431007  0.267863

[334 rows x 5 columns]

In [23]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [24]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.296931,0.326494,0.597773,0.350908,0.723405,0.454261,0.603917,0.57625,0.582318,0.519993,...,0.679552,0.446251,0.56699,0.129665,0.125737,0.770204,0.84509,0.847442,0.67026,0.966893
1,0.323951,0.028997,0.644591,0.010103,0.089767,0.16591,0.379789,0.798433,0.80173,0.365717,...,0.925411,0.553343,0.815366,0.045034,0.992649,0.355958,0.890601,0.691821,0.313709,0.248475
2,0.523106,0.436147,0.629921,0.31883,0.47326,0.840015,0.00044,0.281483,0.419368,0.75884,...,0.985018,0.533052,0.482172,0.79882,0.634353,0.113054,0.863418,0.01404,0.536439,0.639222
3,0.214857,0.70649,0.420055,0.01952,XYZ,0.815756,0.418475,0.039555,0.860366,0.845352,...,0.05275,0.565776,0.727263,0.301114,0.899724,0.24716,0.441534,0.379885,0.950113,0.431007
4,0.183593,0.058738,0.481585,0.4329,0.596523,0.995586,0.316655,0.071987,0.424285,0.617346,...,0.485802,0.595911,0.288881,0.349633,0.503633,0.389445,0.868757,0.166638,0.407011,0.267863

In [25]:
newdf.sort_index(axis=1, ascending=False)

            4         3         2         1         0
0    0.183593  0.214857  0.523106  0.323951  0.296931
1    0.058738   0.70649  0.436147  0.028997  0.326494
2    0.481585  0.420055  0.629921  0.644591  0.597773
3    0.432900   0.01952  0.318830  0.010103  0.350908
4    0.596523       XYZ  0.473260  0.089767  0.723405
..        ...       ...       ...       ...       ...
329  0.389445   0.24716  0.113054  0.355958  0.770204
330  0.868757  0.441534  0.863418  0.890601  0.845090
331  0.166638  0.379885  0.014040  0.691821  0.847442
332  0.407011  0.950113  0.536439  0.313709  0.670260
333  0.267863  0.431007  0.639222  0.248475  0.966893

[334 rows x 5 columns]

In [33]:
newdf.columns = list("ABCDE")

In [34]:
newdf.head()

          A         B         C         D         E
0  0.296931  0.323951  0.523106  0.214857  0.183593
1  0.200000  0.028997  0.436147   0.70649  0.058738
2  0.597773  0.644591  0.629921  0.420055  0.481585
3  0.350908  0.010103  0.318830   0.01952  0.432900
4  0.723405  0.089767  0.473260       XYZ  0.596523

In [40]:
newdf[0, 'B'] = 0.2

In [43]:
newdf

            A         B         C         D         E  (0, B)
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2
4    0.723405  0.089767  0.473260       XYZ  0.596523     0.2
..        ...       ...       ...       ...       ...     ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2

[334 rows x 6 columns]

In [41]:
newdf2 = newdf.copy()

In [47]:
newdf.loc[4,'D']=7.7

In [48]:
newdf

            A         B         C         D         E  (0, B)
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2
..        ...       ...       ...       ...       ...     ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2

[334 rows x 6 columns]

In [49]:
newdf.loc[2,'R']=0.8

In [50]:
newdf

            A         B         C         D         E  (0, B)    R
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2  NaN
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2  NaN
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2  0.8
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2  NaN
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2  NaN
..        ...       ...       ...       ...       ...     ...  ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2  NaN
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2  NaN
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2  NaN
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2  NaN
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2  NaN

[334 rows x 7 columns]

In [54]:
newdf.drop('R',axis=1)

            A         B         C         D         E  (0, B)
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2
..        ...       ...       ...       ...       ...     ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2

[334 rows x 6 columns]

In [55]:
newdf

            A         B         C         D         E  (0, B)    R
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2  NaN
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2  NaN
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2  0.8
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2  NaN
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2  NaN
..        ...       ...       ...       ...       ...     ...  ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2  NaN
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2  NaN
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2  NaN
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2  NaN
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2  NaN

[334 rows x 7 columns]

In [56]:
newdf.drop('R',axis=1,inplace = True)

In [57]:
newdf

            A         B         C         D         E  (0, B)
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2
..        ...       ...       ...       ...       ...     ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2

[334 rows x 6 columns]

In [60]:
newdf.loc[[3,4],['B','E']]

          B         E
3  0.010103  0.432900
4  0.089767  0.596523

In [62]:
newdf.loc[(newdf['A'] < 0.3) & (newdf['C'] > 0.1)]

            A         B         C         D         E  (0, B)
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
15   0.152744  0.485131  0.301605  0.745621  0.094899     0.2
16   0.195702  0.519385  0.961307   0.09547  0.393729     0.2
18   0.241198  0.723801  0.807928  0.998871  0.382803     0.2
..        ...       ...       ...       ...       ...     ...
320  0.058395  0.915926  0.297231  0.412421  0.629326     0.2
321  0.218002  0.708473  0.887501  0.346589  0.280254     0.2
322  0.297947  0.177150  0.985814  0.504523  0.100681     0.2
327  0.129665  0.045034  0.798820  0.301114  0.349633     0.2
328  0.125737  0.992649  0.634353  0.899724  0.503633     0.2

[95 rows x 6 columns]

In [63]:
newdf.iloc[0,4]

np.float64(0.18359260312296866)

In [64]:
newdf.iloc[[0,5],[1,2]]

         B         C
0  0.20000  0.523106
5  0.16591  0.840015

In [65]:
newdf.drop(4)

            A         B         C         D         E  (0, B)
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2
5    0.454261  0.165910  0.840015  0.815756  0.995586     0.2
..        ...       ...       ...       ...       ...     ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2

[333 rows x 6 columns]

In [66]:
newdf.dropna()

            A         B         C         D         E  (0, B)
0    0.296931  0.200000  0.523106  0.214857  0.183593     0.2
1    0.200000  0.028997  0.436147   0.70649  0.058738     0.2
2    0.597773  0.644591  0.629921  0.420055  0.481585     0.2
3    0.350908  0.010103  0.318830   0.01952  0.432900     0.2
4    0.723405  0.089767  0.473260       7.7  0.596523     0.2
..        ...       ...       ...       ...       ...     ...
329  0.770204  0.355958  0.113054   0.24716  0.389445     0.2
330  0.845090  0.890601  0.863418  0.441534  0.868757     0.2
331  0.847442  0.691821  0.014040  0.379885  0.166638     0.2
332  0.670260  0.313709  0.536439  0.950113  0.407011     0.2
333  0.966893  0.248475  0.639222  0.431007  0.267863     0.2

[334 rows x 6 columns]

In [67]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 334, dtype: bool

In [68]:
newdf['C']= None

In [69]:
newdf.dropna(how='all')

            A         B     C         D         E  (0, B)
0    0.296931  0.200000  None  0.214857  0.183593     0.2
1    0.200000  0.028997  None   0.70649  0.058738     0.2
2    0.597773  0.644591  None  0.420055  0.481585     0.2
3    0.350908  0.010103  None   0.01952  0.432900     0.2
4    0.723405  0.089767  None       7.7  0.596523     0.2
..        ...       ...   ...       ...       ...     ...
329  0.770204  0.355958  None   0.24716  0.389445     0.2
330  0.845090  0.890601  None  0.441534  0.868757     0.2
331  0.847442  0.691821  None  0.379885  0.166638     0.2
332  0.670260  0.313709  None  0.950113  0.407011     0.2
333  0.966893  0.248475  None  0.431007  0.267863     0.2

[334 rows x 6 columns]